# Generated by Django 3.1.2 on 2021-07-22 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Posts', '0003_auto_20210722_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='posts',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_posts_like', to='Posts.post'),
        ),
    ]
