# Generated by Django 3.1.2 on 2021-07-22 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0002_auto_20210718_2233'),
        ('Posts', '0004_auto_20210722_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='posts',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_posts_like', to='Profile.profile'),
        ),
    ]
