# Generated by Django 3.1.2 on 2021-07-30 12:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Profile', '0003_relationship'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='message',
            field=models.ManyToManyField(blank=True, related_name='inblox_message', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=250)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('sended_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sended_by', to='Profile.profile')),
                ('sended_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sended_to', to='Profile.profile')),
            ],
        ),
    ]
