# Generated by Django 3.1.2 on 2021-07-30 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0004_auto_20210730_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='body',
            field=models.TextField(max_length=250),
        ),
    ]
