# Generated by Django 3.2.6 on 2021-08-29 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0006_auto_20210817_2320'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('requirement', models.TextField()),
                ('experience', models.CharField(choices=[('1', '0'), ('2', '1-5'), ('3', 'more than 5')], max_length=200)),
                ('filled', models.BooleanField(default=False)),
            ],
        ),
    ]
