# Generated by Django 3.2.6 on 2021-08-31 18:12

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0009_applicant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='applicant',
            field=models.CharField(default=django.contrib.auth.models.User, max_length=200),
        ),
    ]
