# Generated by Django 3.2.6 on 2021-08-31 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0010_alter_applicant_applicant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applicant', to='Profile.profile'),
        ),
    ]
