# Generated by Django 3.2.6 on 2021-09-05 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0011_alter_applicant_applicant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='cover',
            field=models.ImageField(blank=True, default='Profile/avatar.png', upload_to='profile_picture'),
        ),
    ]
